sources:
  docker_logs:
    type: docker_logs
    include_containers:
      - server
      - victoriametrics
      - vmagent
      - victorialogs
      - vmauth
      - grafana
    # Automatically discover and collect logs from specified Docker containers.
    # For production, consider using `include_labels` or `include_container_names`
    # to target specific applications rather than all.

sinks:
  victorialogs_sink:
    type: http
    inputs:
      - docker_logs
    uri: "http://victorialogs:9428/insert/jsonline?_stream_fields=container_name,image,source_type&_msg_field=message&_time_field=timestamp"
    compression: gzip
    encoding:
      codec: json
    framing:
      method: newline_delimited
    healthcheck:
      enabled: false
    # Send logs to VictoriaLogs via its JSON line ingestion API.
    # _stream_fields: Fields used to identify a unique log stream (e.g., container_name, image).
    # _msg_field: The field containing the actual log message.
    # _time_field: The field containing the timestamp of the log entry.
