{
 "title": "Server",
 "tags": [ "server" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_http_requests_total{instance=\"server:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_go_goroutines{instance=\"server:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_cpu_utilization_percent{instance=\"server:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% RAM Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_memory_usage_bytes{instance=\"server:3000\", type=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}